name: Buscar Noticias de IA en Odontología

on:
  schedule:
    - cron: '0 * * * *'  # Ejecuta cada hora
  workflow_dispatch:     # Permite ejecución manual
  push:
    paths:
      - 'buscar_noticias.py'
      - 'requirements.txt'

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # 1. Clona tu repositorio
      - name: Checkout del repositorio
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2. Configura Python
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      # 3. Instala las dependencias
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install requests deep-translator python-dateutil

      # 4. Ejecuta tu script de Python
      - name: Ejecutar script de búsqueda de noticias
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: python buscar_noticias.py

      # 5. Verifica los archivos creados (para debug)
      - name: Listar archivos generados
        run: |
          echo "=== Estructura de carpetas ==="
          find . -name "*.md" -type f | head -20
          echo "=== Contenido de noticias_en ==="
          ls -la noticias_en/ 2>/dev/null || echo "Carpeta noticias_en no existe"
          echo "=== Contenido de noticias_es ==="
          ls -la noticias_es/ 2>/dev/null || echo "Carpeta noticias_es no existe"

      # 6. Sube los cambios
      - name: Confirmar y subir cambios
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "📰 Actualización automática de noticias - $(date +'%Y-%m-%d %H:%M')"
          file_pattern: |
            noticias_en/*.md
            noticias_es/*.md
            noticias/*.md
            noticias_traducidas/*.md
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          commit_options: '--signoff'
          push_options: '--force'
          skip_fetch: true
          status_options: '--untracked-files=all'
