name: Buscar Noticias de IA en Odontología

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1. Clona el repositorio
      - name: Checkout del repositorio
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      # 2. Configura Python
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Instala dependencias
      - name: Instalar dependencias
        run: |
          pip install requests deep-translator

      # 4. Ejecuta el script
      - name: Ejecutar script de noticias
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: python buscar_noticias.py

      # 5. DEBUG: Verificar qué se creó
      - name: Verificar archivos creados
        run: |
          echo "=== ESTRUCTURA COMPLETA ==="
          find . -name "*.md" -type f | sort
          echo "=== CONTENIDO DE CARPETAS ==="
          ls -la noticias_en/ || echo "noticias_en no existe"
          ls -la noticias_es/ || echo "noticias_es no existe"
          echo "=== CONTENIDO DE ARCHIVOS ==="
          cat noticias_en/2025-10-27.md || echo "No se puede leer archivo EN"
          cat noticias_es/2025-10-27.md || echo "No se puede leer archivo ES"

      # 6. Forzar la detección de cambios
      - name: Configurar Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Ver estado de Git
        run: |
          echo "=== ESTADO GIT ==="
          git status
          echo "=== ARCHIVOS MODIFICADOS/NUEVOS ==="
          git ls-files --modified --others --exclude-standard

      # 7. Commit y push MEJORADO
      - name: Commit y push de cambios
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "📰 Actualización automática de noticias"
          file_pattern: |
            noticias_en/**
            noticias_es/**
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          commit_options: '--allow-empty'
          disable_globbing: false
