name: Buscar Noticias de IA en Odontología

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write # <-- AÑADE ESTE BLOQUE

    steps:
      # 1. Clona tu repositorio para que el script tenga acceso a él
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      # 2. Configura Python
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      # 3. Instala las dependencias
      - name: Instalar dependencias
        run: pip install -r requirements.txt

      # 4. Ejecuta tu script de Python
      - name: Ejecutar script de búsqueda de noticias
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: python buscar_noticias.py

      # 5. Sube los cambios (archivos traducidos y originales)
      - name: Confirmar y subir cambios
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "📰 Actualización automática de noticias"
          file_pattern: |
            noticias/*.md
            noticias_traducidas/*.md
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
